#-------------------------------
# Site Settings
title: ZRC Ceramics
logo: # '/images/ruicheng.png' # You can add own logo. For example '/images/logo.png'.
author: Jiaxin
description: Clancy is a elegant portfolio theme for Jekyll.


#-------------------------------
# Menu Settings
menu__settings:
  menu__items:
    - title: 'Home'
      url: '/'
    - title: 'Products'
      url: '/blog/'
    - title: 'About'
      url: '/about/'
    - title: 'Contact'
      url: '/contact/'
    - title: 'Elements'
      url: '/images/handbook.pdf'


#-------------------------------
# Hero Settings
hero:
  hero__description:  Manufactor of Wall and Floor Tiles, OEM, wholesaler and Related Products.
  hero__title: Better products, better prices. Tiles experts around you!

#-------------------------------
# Portfolio Settings
portfolio:
  portfolio__title: Portfolio
  portfolio__gallery:
    - image: /images/tile1.jpg
      title: PW-IZMIR-G  PW-IZMIR-DG
      description: 咖啡厅

    - image: /images/tile2.jpg
      title: ICM60024 亚光甩点+云母片
      description: 客厅 600X600

    - image: /images/tile3.jpg
      title: TS62601 TS82601 TS122601
      description: 西餐厅 600X600mm

    - image: /images/tile4.jpg
      title: TS62510 TS82510
      description: 品牌服饰店 600X600mm

    - image: /images/tile5.jpg
      title: ICM680041 亚光
      description: 客厅/办公室 600X600mm

    - image: /images/tile6.jpg
      title: ICM68888 亚光
      description: 客厅/餐厅/工作室 600X600mm

    - image: /images/tile7.jpg
      title: YT369104 YT69104 YT89104 YT129104
      description: 悦陶陶瓷/一石多面 SPA休闲会所 800X800mm

    - image: /images/tile8.jpg
      title: TS32620 TS62620 TS82620 TS122620
      description: 一石多面/别墅庭院 600X1200mm

    - image: /images/tile9.jpg
      title: TS62605 TS82605
      description: 办公室 600X600mm


#-------------------------------
# Subscribe Settings
mailchimp:
  mailchimp__title: Get updates and digital art inspiration # Add your Title
  mailchimp__identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
  mailchimp__button__text: Subscribe # Add your button text.
  mailchimp__bg__color: "#f2eef8" # To change the color of the figure, add a hexadecimal color code (HEX). For example - "#f2eef8" (You can generate any color here - https://htmlcolorcodes.com/).


#-------------------------------
# Footer Settings
social:
- {icon: "ion-logo-twitter", color: "#55acee", label: Twitter, link: "https://twitter.com"}
- {icon: "ion-logo-facebook", color: "#3b5999", label: Facebook, link: "https://facebook.com"}
- {icon: "ion-logo-pinterest", color: "#bd081c", label: Pinterest, link: "https://pinterest.com"}
- {icon: "ion-logo-dribbble", color: "#ea4c89", label: Dribbble, link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", color: "#e4405f", label: Instagram, link: "https://instagram.com"}
- {icon: "ion ion-logo-vimeo", color: "#1393cd", label: Vimeo, link: "https://vimeo.com"}

# Example of adding a new link to the footer section - {icon: "ion-logo-github", color: "#24292e, label: Github, link: "https://github.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Contact Settings
contact:
  email: woopsdsn@163.com # Add your email for contact form
  description: Ruicheng comes with a built-in contact form, or you can contact us by email woopsdsn@163.com # Add a description of your form.

# NOTE
# Clancy comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Comment Section (Disqus)

disqus-identifier: anvodstudio-demo # add your shortname for Disqus Comment. For example anvodstudio-demo


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.
